steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_GEMINI_API_KEY=$$VITE_GEMINI_API_KEY \
          -t gcr.io/$PROJECT_ID/ynm-drishti:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/ynm-drishti:latest \
          .
    secretEnv: ['VITE_GEMINI_API_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ynm-drishti:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ynm-drishti:latest']

images:
  - 'gcr.io/$PROJECT_ID/ynm-drishti:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ynm-drishti:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_GEMINI_API_KEY/versions/latest
      env: 'VITE_GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
